# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'waterDisposal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for waterDisposal
    pod 'FirebaseMessaging'

  

  target 'waterDisposalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'waterDisposal-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for waterDisposal-tvOS

  target 'waterDisposal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
